### ISSUE TITLE
[Bug] Netlify/Vercel deploy crashes on directly going to any route other than / in SPA mode

### ISSUE THREAD

**Issue by vanillacode314** [solidjs/solid-start#303]
## Error
```
TypeError: event.env.getStaticHTML is not a function
    at /var/task/netlify/functions/index.js:13920:30
    at /var/task/netlify/functions/index.js:14386:29
    at /var/task/netlify/functions/index.js:14141:18
    at /var/task/netlify/functions/index.js:14406:7
    at Runtime.handler (/var/task/netlify/functions/index.js:14417:24)
    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1028:29)
```

Route: https://solidjs--redditlattice.netlify.app/r/wallpapers
Source Code: https://github.com/vanillacode314/redditlattice/tree/solidjs

Repro: Just visit the route

Going to / and then going to any other route works but not when visiting the route directly

**Comment by vanillacode314** [comment]
Currently, this is the only thing stopping me from publishing my app to prod :(

**Comment by nksaraf** [comment]
Thanks for reporting.. yeah feels like a bug from our side

**Comment by vanillacode314** [comment]
I did some digging apparently its the `renderAsync` function it expects a getStaticHTML function but only edge mode provides that, tried edge mode but it has other problems.

**Comment by nksaraf** [comment]
yeah that's close to the solution... I need to figure out how to get the HTML page during a request for a non-html route, im assuming this is the ssr: false mode. Maybe you can try the normal `netlify` adapter with ssr until we fix this, like not SPA mode.

**Comment by vanillacode314** [comment]
well wouldn't for an spa index.html should be served regardless of the route?

**Comment by vanillacode314** [comment]
other frameworks usually don't use serverless functions in spa mode and only serves /index.html as a static file. The user is required to redirect all 404s to /index.html to handle spa mode.

**Comment by vanillacode314** [comment]
managed to find a workaround which I believe is pretty close to the solution. I added these redirect rules to my netlify site
```
/trpc/* /.netlify/functions/index 200
/* /index.html 200
```
I know the trpc one is specific to my case but I presume that solid-start would be able to generate these redirects at build time for api routes automatically

**Comment by vanillacode314** [comment]
fixed

**Comment by vanillacode314** [comment]
issue reappeared on updating solid-start

**Comment by ryansolid** [comment]
I agree that we probably shouldn't be handling this and that the provider redirects should which are adapter specific and would require knowledge of ssr: false.. which we do have but how to do so without conflicting with others is interesting. I'm not sure if we can just automate this. So I'd recommend manual redirects.

In any case with manual redirects I'm a bit surprised this is an issue still. Can you confirm?

**Comment by vanillacode314** [comment]
Repo: https://github.com/vanillacode314/solid-start-repro-issue-303
Deploy without manual redirects: https://dashing-croquembouche-63b3bb.netlify.app
Deploy with manual redirects: https://manual-redirect--dashing-croquembouche-63b3bb.netlify.app/

Context:
- Two routes / and /about
- without manual redirects crash on visiting /about directly
- with manual redirects no crash on visiting /about directly

The reason solid-start should be able to handle this without manual redirects is because it deploy a serverless function even in spa mode which means it can serve index.html directly from the function if the route requested is not an API route.

Another way to move forward is to drop the serverless functions completely in ssr: false which would shift the burden to the user and would act as static adapter and not support API routes (this is the approach sveltekit takes)

**Comment by ryansolid** [comment]
Yeah I'm pretty tempted to drop server in ssr: false. This idea of doing both was something that Nikhil thought of, but it has made things really complicated.

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed in mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
